### ISSUE TITLE
Add Autoencoder

### ISSUE THREAD

**Issue by Flammrock** [Flammrock/protein-structural-autoencoder#1]
## Description including problem, use cases, benefits, and/or goals

To build the autoencoder for analysis purpose, we need a [Neural Network](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/NeuralNetwork.java) which takes as input a [Contact Map](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/bio/ContactMap.java).

**Autoencoders** are designed as below :

![1_44eDEuZBEsmG_TCAKRI3Kw@2x](https://user-images.githubusercontent.com/17354261/155853484-16004313-885f-4009-aa88-3a7c4a986988.png)

So basically, **Autoencoders** are composed by a **Encoder** and a **Decoder**. The particularity is that the _input layer_ and the _output layer_ have the same size. When using a **_trained_ Autoencoder**, after forward propagation the _output_ must be very close to the corresponding _input_.

Between the **Encoder** and the **Decoder**, there is a little layer that allow to compress data and to have a new representation of the _input_.

## Proposal

By the way, we can build a neural network from scratch. But for integration purpose, it will be nice to use an existing library that already do that. We can use [DeepLearning4J](https://github.com/eclipse/deeplearning4j) to achieve that. For more flexibility, we can wrap a neural network built with [DeepLearning4J](https://github.com/eclipse/deeplearning4j).

I think we can manage the class as below :

![Capture d’écran 2022-02-26 194435](https://user-images.githubusercontent.com/17354261/155855345-7d785706-40e7-40da-85ae-402d33226ad4.png)

And as I said, NeuralNetwork would be a wrapper of [DeepLearning4J](https://github.com/eclipse/deeplearning4j) to add more flexibility if we decide to use another implementation.

## TODO List

- [ ] import [DeepLearning4J](https://github.com/eclipse/deeplearning4j) to the project
- [ ] create the [Neural Network](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/NeuralNetwork.java) class
- [ ] create a JUnit test that train a neural network to predicate the **XOR Function**
- [ ] create the [Autoencoder](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/Autoencoder.java) class
- [ ] create a JUnit test for the [Autoencoder](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/Autoencoder.java) class

## Links / references

https://github.com/eclipse/deeplearning4j
https://towardsdatascience.com/understanding-and-implementing-neural-networks-in-java-from-scratch-61421bb6352c
