### ISSUE TITLE
Add Cluster algorithm

### ISSUE THREAD

**Issue by Flammrock** [Flammrock/protein-structural-autoencoder#2]
## Description including problem, use cases, benefits, and/or goals

After using the **Autoencoder** to encode [Fragment](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/bio/Fragment.java)'s [Contact Map](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/bio/ContactMap.java), we need to clusterize all compressed data computed by the **Autoencoder**.

To clusterize these compressed data, we need to project these data on a 2d plot by using [Multidimensional Scaling](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/MultidimensionalScaling.java). We end up with a list of points (with x and y coordinates).

For instance, if we have :

![Capture d’écran 2022-02-26 212008](https://user-images.githubusercontent.com/17354261/155857939-96a3a0b6-cf93-4122-b8e6-939aab473898.png)

We should clustering in 3 group like below :

![Capture d’écran 2022-02-26 212020](https://user-images.githubusercontent.com/17354261/155857968-81b7496b-78a3-4b56-89e7-60797328fdab.png)

There are many clustering algorithm :

![Capture d’écran 2022-02-26 212504](https://user-images.githubusercontent.com/17354261/155858101-540178ef-370c-4a4b-ae74-76d7095eb93f.png)

## Proposal

I propose to use K-means[^1] to achieve that. Maybe we should create a ``cluster`` package to add in it all clustering algorithms.

We should implement this with this design below :

![Capture d’écran 2022-02-26 215302](https://user-images.githubusercontent.com/17354261/155858754-13b5f45a-759f-4def-9a70-c5bd3405d06a.png)

The Enumeration should look like that :

```java
public enum ClusterMethod {

     KMeans() {
          @Override
          public List<ClusterPoint<?>> clusterize(List<ClusterPoint<?>> points) { 
               // implement K-Means here
          }
     },
     OtherMethod() {
          @Override
          public List<ClusterPoint<?>> clusterize(List<ClusterPoint<?>> points) { 
               // implement an other method here
          }
     };

     public abstract List<ClusterPoint<?>> clusterize(List<ClusterPoint<?>> points);
}
```

It's not the final design and I think we will need other classes but the most important is already said.

## TODO List

- [ ] create the cluster package
- [ ] create the ClusterPoint class
- [ ] create the Cluster class
- [ ] create the ClusterMethod enum
- [ ] implement the K-Means algorithm in the ClusterMethod enum
- [ ] create a JUnit test with basic data

## Links / references

[^1]: explained here : https://www.baeldung.com/java-k-means-clustering-algorithm
