### ISSUE TITLE
Add setup wizard gui to generate an autoencoder with specified parameters

### ISSUE THREAD

**Issue by Flammrock** [Flammrock/protein-structural-autoencoder#3]
## Description including problem, use cases, benefits, and/or goals

We need to add something to allow to the user to generate structual alphabet with an autoencoder. The user should be able to manage some parameters to configure the autoencoder and the whole process which is :

![Capture d’écran 2022-02-26 223024](https://user-images.githubusercontent.com/17354261/155859692-b1059201-22a7-49d8-83de-4dcfd35b0af5.png)

## Proposal

The user should be able to choose the fragment size, maybe the logistic function, and more important the structure of the autoencoder which include the amount of hidden layers, the amount of neuron for each layer (and maybe the activation function, and the backpropagation method).

According to that, the user should be able to define the dataset to train the autoencoder.

## TODO List

- [ ] allow multiple [Window](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/display/internal/Window.java) in the [Application](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/display/Application.java)
- [ ] add the setup wizard in the [Menu](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/display/Menu.java)
![Capture d’écran 2022-02-26 223817](https://user-images.githubusercontent.com/17354261/155859978-e5baf872-6d19-49ce-8f95-91b38dba0146.png)
- [ ] the setup wizard must create an [Autoencoder](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/autoencoder/Autoencoder.java) at the end
