### ISSUE TITLE
Add a full support for PDB Parsing

### ISSUE THREAD

**Issue by Flammrock** [Flammrock/protein-structural-autoencoder#6]
## Description including problem, use cases, benefits, and/or goals

We partially support the parsing of PDB Files according to this commit : 7a9de69caad225a804dade6c983b61179041a45d. However, according to the documentation[^1], we need to add a support for sub-record.

For instance, the **REMARK** record is defined like that :

| COLUMNS | DATA TYPE   | FIELD     | DEFINITION                                                                                    |
|---------|-------------|-----------|-----------------------------------------------------------------------------------------------|
| 1 - 6   | Record name | "REMARK"  |                                                                                               |
| 8 - 10  | Integer     | remarkNum | Remark number. It is not an error for remark n to exist in an entry when remark n-1 does not. |
| 12 - 79 | LString     | empty     | Left as white space in first line of each new remark.                                         |

And the **REFERENCE** record is a sub-record of the **REMARK** record and it's defined like that :

| COLUMNS | DATA TYPE   | FIELD       | DEFINITION                                           |
|---------|-------------|-------------|------------------------------------------------------|
| 1 - 6   | Record name | "REMARK"    |                                                      |
| 10      | LString(1)  | "1"         |                                                      |
| 12 - 20 | LString(9)  | "REFERENCE" |                                                      |
| 22 - 70 | Integer     | refNum      | Reference number. Starts with 1 and increments by 1. |

Another issue is to merge record that have the field "continuation" like this record :

| COLUMNS | DATA TYPE    | FIELD        | DEFINITION                                |
|---------|--------------|--------------|-------------------------------------------|
| 1 - 6   | Record name  | "TITLE"      |                                           |
| 9 - 10  | Continuation | continuation | Allows concatenation of multiple records. |
| 12 - 20 | String       | title        | Title of the experiment.                  |

There are records missing like : **DBREF**, **HET**, **HETNAM**, **HETSYN**, **FORMUL**, **HELIX**, **SHEET**, **SSBOND**, **LINK**, **CISPEP**, **SITE**, **CRYST1**, **ORIGXn**, **SCALEn**, **MTRIXn**, **MODEL**

## Proposal

Maybe we should add missing records like that  in the Enum :

```java
	HEADER(new PDBField.Builder()
		.add(1,6,"Record name","HEADER")
		.add(11,50,"String(40)","classification")
		.add(51,59,"Date","depDate")
		.add(63,66,"IDcode","idCode")
		.build()
	),
```

And I think we can do the parsing in two step.

- first step : parse each line individually ;
- second step : merge all record that have the **Continuation**  field.

I think we must add some code in the base class to split list string with comma.

We need also to support each type :

| DATA TYPE          | DESCRIPTION                                                                                                                                                                                                                                                 |
|--------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| AChar              | An alphabetic character (A-Z, a-z).                                                                                                                                                                                                                         |
| Atom               | Atom name.                                                                                                                                                                                                                                                  |
| Character          | Any non-control character in the ASCII character set or a space.                                                                                                                                                                                            |
| Continuation       | A two-character field that is either blank (for the first record of a set) or contains a two digit number right-justified and blank-filled which counts continuation records starting with 2. The continuation number must be followed by a blank.          |
| Date               | A 9 character string in the form DD-MMM-YY where DD is the day of the month, zero-filled on the left (e.g., 04); MMM is the common English 3-letter abbreviation of the month; and YY is the last two digits of the year. This must represent a valid date. |
| IDcode             | A PDB identification code which consists of 4 characters, the first of which is a digit in the range 0 - 9; the remaining 3 are alpha-numeric, and letters are upper case only. Entries with a 0 as the first character do not contain coordinate data.     |
| Integer            | Right-justified blank-filled integer value.                                                                                                                                                                                                                 |
| Token              | A sequence of non-space characters followed by a colon and a space.                                                                                                                                                                                         |
| List               | A String that is composed of text separated with commas.                                                                                                                                                                                                    |
| LString            | A literal string of characters. All spacing is significant and must be preserved.                                                                                                                                                                           |
| LString(n)         | An LString with exactly n characters.                                                                                                                                                                                                                       |
| Real(n,m)          | Real (floating point) number in the FORTRAN format Fn.m.                                                                                                                                                                                                    |
| Record name        | The name of the record: 6 characters, left-justified and blank-filled.                                                                                                                                                                                      |
| Residue name       | One of the standard amino acid or nucleic acids, as listed below, or the non-standard group designation as defined in the HET dictionary. Field is right-justified.                                                                                         |
| SList              | A String that is composed of text separated with semi-colons.                                                                                                                                                                                               |
| Specification      | A String composed of a token and its associated value separated by a colon.                                                                                                                                                                                 |
| Specification List | A sequence of Specifications, separated by semi-colons.                                                                                                                                                                                                     |
| String             | A sequence of characters. These characters may have arbitrary spacing, but should be interpreted as directed below.                                                                                                                                         |
| String(n)          | A String with exactly n characters.                                                                                                                                                                                                                         |
| SymOP              | An integer field of from 4 to 6 digits, right-justified, of the form nnnMMM where nnn is the symmetry operator number and MMM is the translation vector.                                                                                                    |

## TODO List

- [ ] add a package ``types`` in ``bio.pdb``
- [ ] create a base class which will have method to parse String to Integer/Float/List\<String\>
- [ ] create as many classes as there are types and each class extends the base class
- [ ] bind this package to [Record.java](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/bio/pdb/Record.java)
- [ ] add the second step in [File.java](https://github.com/Flammrock/protein-structural-autoencoder/blob/main/protein_structural_autoencoder/src/bio/pdb/File.java)

## Links / references

[^1]: reference https://ftp.wwpdb.org/pub/pdb/doc/format_descriptions/Format_v33_A4.pdf
